[theme]
# we use image as back-ground so we disable primary color and secondary colors for back-ground
#primaryColor="#F63366"
#backgroundColor="#000000"
#secondaryBackgroundColor="#C4CAD0"
textColor="#FCF7FF"
font="Press Start 2P"
